name: Python CI/CD Demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 📦 Install dependencies
        run: |
          pip install -r requirements.txt

      - name: 🧪 Run tests
        run: |
          pytest || exit 1

      - name: 💬 Reply message
        if: success()
        run: echo "✅ All tests passed successfully!"

      # 🧱 الخطوة الجديدة: النشر
      - name: 🚀 Deploy application
        if: success()    # تعمل فقط إذا نجح الاختبار
        run: |
          echo "🚀 Starting deployment..."
          mkdir build_output
          cp -r * build_output/
          echo "✅ Deployment complete!"
